import { 
  UserProfile, 
  SubsidiaryEntity, 
  BusinessUnitEntity, 
  ProjectEntity, 
  ESGMetricItem, 
  BRSRIndicator, 
  ValidationAlert, 
  ApprovalRecord, 
  AuditTrailRecord, 
  SDGItem 
} from '../types';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'u-1',
    name: 'Rajesh Verma',
    email: 'rajesh.verma@meil.in',
    corporateId: 'EMP-PU-1042',
    password: 'Password@123',
    role: 'project_user',
    roleTitle: 'Project Sustainability Lead',
    organization: 'MEIL Group',
    subsidiary: 'Clean Energy & Infrastructure Ltd',
    businessUnit: 'Solar Energy BU',
    project: 'Solar Mega-Park 500MW (SMP-500)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'u-2',
    name: 'Vikram Malhotra',
    email: 'vikram.malhotra@meil.in',
    corporateId: 'EMP-PM-2089',
    password: 'Password@123',
    role: 'bu_manager',
    roleTitle: 'Project & Business Unit Manager',
    organization: 'MEIL Group',
    subsidiary: 'Clean Energy & Infrastructure Ltd',
    businessUnit: 'Solar Energy BU',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'u-3',
    name: 'Sunita Rao',
    email: 'sunita.rao@meil.in',
    corporateId: 'EMP-SA-3150',
    password: 'Password@123',
    role: 'subsidiary_admin',
    roleTitle: 'Subsidiary Director of ESG & EHS',
    organization: 'MEIL Group',
    subsidiary: 'Clean Energy & Infrastructure Ltd',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'u-4',
    name: 'Dr. Ananya Sen',
    email: 'ananya.sen@meil.in',
    corporateId: 'EMP-ESG-4021',
    password: 'Password@123',
    role: 'esg_team',
    roleTitle: 'Group Chief Sustainability Officer',
    organization: 'MEIL Group',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'u-5',
    name: 'Rekha Nair',
    email: 'rekha.nair@meil.in',
    corporateId: 'EMP-GA-9001',
    password: 'Password@123',
    role: 'group_admin',
    roleTitle: 'Group Executive VP & Compliance Officer',
    organization: 'MEIL Group',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'u-6',
    name: 'Deepak Khaitan',
    email: 'deepak.khaitan@meil.in',
    corporateId: 'EMP-EXEC-001',
    password: 'Password@123',
    role: 'management',
    roleTitle: 'Managing Director & Board ESG Chair',
    organization: 'MEIL Group',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80'
  },
  // Legacy aliases for backward compatibility
  {
    id: 'u-1-alias',
    name: 'Rajesh Verma (Apex)',
    email: 'rajesh.v@apexinfratech.com',
    corporateId: 'APX-1042',
    password: 'Password@123',
    role: 'project_user',
    roleTitle: 'Project Sustainability Lead',
    organization: 'Apex Infrastructure Group',
    subsidiary: 'Apex Heavy Engineering & Construction',
    businessUnit: 'Renewables & Power Transmission',
    project: 'Solar Mega-Park 500MW (SMP-500)'
  },
  {
    id: 'u-2-alias',
    name: 'Sunita Rao (Apex)',
    email: 'sunita.rao@apexinfratech.com',
    corporateId: 'APX-2089',
    password: 'Password@123',
    role: 'bu_manager',
    roleTitle: 'Business Unit General Manager',
    organization: 'Apex Infrastructure Group',
    subsidiary: 'Apex Heavy Engineering & Construction',
    businessUnit: 'Renewables & Power Transmission'
  },
  {
    id: 'u-4-alias',
    name: 'Dr. Ananya Sen (Apex)',
    email: 'ananya.sen@apexinfratech.com',
    corporateId: 'APX-4021',
    password: 'Password@123',
    role: 'esg_team',
    roleTitle: 'Chief Sustainability Officer',
    organization: 'Apex Infrastructure Group'
  },
  {
    id: 'u-5-alias',
    name: 'Arvind Mehra (Apex)',
    email: 'arvind.mehra@apexinfratech.com',
    corporateId: 'APX-9001',
    password: 'Password@123',
    role: 'group_admin',
    roleTitle: 'Group Executive VP & Compliance Officer',
    organization: 'Apex Infrastructure Group'
  },
  {
    id: 'u-6-alias',
    name: 'Priya Nair (Apex)',
    email: 'priya.nair@apexinfratech.com',
    corporateId: 'APX-001',
    password: 'Password@123',
    role: 'management',
    roleTitle: 'Board Member & ESG Committee Chair',
    organization: 'Apex Infrastructure Group'
  }
];

export const MOCK_SUBSIDIARIES: SubsidiaryEntity[] = [
  {
    id: 'sub-1',
    name: 'Apex Heavy Engineering & Construction',
    code: 'AHEC',
    businessUnitsCount: 3,
    projectsCount: 8,
    esgCompletion: 92,
    brsrCompletion: 88,
    leadAdmin: 'Vikramaditya Patel'
  },
  {
    id: 'sub-2',
    name: 'Apex Smart Infrastructure & Urban Mobility',
    code: 'ASIUM',
    businessUnitsCount: 2,
    projectsCount: 6,
    esgCompletion: 84,
    brsrCompletion: 79,
    leadAdmin: 'Meera Krishnan'
  },
  {
    id: 'sub-3',
    name: 'Apex Green Energy & Utility Services',
    code: 'AGEUS',
    businessUnitsCount: 2,
    projectsCount: 4,
    esgCompletion: 96,
    brsrCompletion: 94,
    leadAdmin: 'Tariq Al-Mansoor'
  }
];

export const MOCK_BUSINESS_UNITS: BusinessUnitEntity[] = [
  {
    id: 'bu-1',
    name: 'Renewables & Power Transmission',
    subsidiaryId: 'sub-1',
    projectsCount: 4,
    esgCompletion: 94,
    brsrCompletion: 91,
    headOfUnit: 'Sunita Rao'
  },
  {
    id: 'bu-2',
    name: 'Hydrocarbon & Heavy EPC',
    subsidiaryId: 'sub-1',
    projectsCount: 4,
    esgCompletion: 90,
    brsrCompletion: 85,
    headOfUnit: 'Devendra Joshi'
  },
  {
    id: 'bu-3',
    name: 'Metro Rail & Transit Systems',
    subsidiaryId: 'sub-2',
    projectsCount: 3,
    esgCompletion: 87,
    brsrCompletion: 82,
    headOfUnit: 'Karan Singhal'
  },
  {
    id: 'bu-4',
    name: 'Water & Industrial Effluent Treatment',
    subsidiaryId: 'sub-2',
    projectsCount: 3,
    esgCompletion: 81,
    brsrCompletion: 76,
    headOfUnit: 'Nandini Das'
  }
];

export const MOCK_PROJECTS: ProjectEntity[] = [
  {
    id: 'proj-1',
    code: 'SMP-500',
    name: 'Solar Mega-Park 500MW Facility',
    subsidiaryId: 'sub-1',
    subsidiaryName: 'Apex Heavy Engineering & Construction',
    businessUnitId: 'bu-1',
    businessUnitName: 'Renewables & Power Transmission',
    location: 'Bhadla, Rajasthan',
    state: 'Rajasthan',
    esgCompletion: 95,
    brsrCompletion: 92,
    validationStatus: 'clean',
    approvalStatus: 'approved',
    lastUpdated: '2026-03-28',
    leadPerson: 'Rajesh Verma'
  },
  {
    id: 'proj-2',
    code: 'HVDC-SOUTH',
    name: 'High Voltage Direct Current Transmission Corridor',
    subsidiaryId: 'sub-1',
    subsidiaryName: 'Apex Heavy Engineering & Construction',
    businessUnitId: 'bu-1',
    businessUnitName: 'Renewables & Power Transmission',
    location: 'Raigarh to Pugalur',
    state: 'Tamil Nadu',
    esgCompletion: 88,
    brsrCompletion: 84,
    validationStatus: 'has_warnings',
    approvalStatus: 'under_review',
    lastUpdated: '2026-03-26',
    leadPerson: 'Amitabh Sanyal'
  },
  {
    id: 'proj-3',
    code: 'GH2-01',
    name: 'Green Hydrogen Electrolyzer Pilot Plant',
    subsidiaryId: 'sub-1',
    subsidiaryName: 'Apex Heavy Engineering & Construction',
    businessUnitId: 'bu-2',
    businessUnitName: 'Hydrocarbon & Heavy EPC',
    location: 'Hazira Industrial Zone',
    state: 'Gujarat',
    esgCompletion: 78,
    brsrCompletion: 74,
    validationStatus: 'has_warnings',
    approvalStatus: 'correction_required',
    lastUpdated: '2026-03-25',
    leadPerson: 'Manish Chawla'
  },
  {
    id: 'proj-4',
    code: 'METRO-L3',
    name: 'Urban Elevated Metro Corridor Phase 3',
    subsidiaryId: 'sub-2',
    subsidiaryName: 'Apex Smart Infrastructure & Urban Mobility',
    businessUnitId: 'bu-3',
    businessUnitName: 'Metro Rail & Transit Systems',
    location: 'Bengaluru Metro Sector',
    state: 'Karnataka',
    esgCompletion: 91,
    brsrCompletion: 89,
    validationStatus: 'clean',
    approvalStatus: 'validated',
    lastUpdated: '2026-03-27',
    leadPerson: 'Pooja Hegde'
  },
  {
    id: 'proj-5',
    code: 'WWRP-02',
    name: 'Municipal Wastewater Reclamation Plant',
    subsidiaryId: 'sub-2',
    subsidiaryName: 'Apex Smart Infrastructure & Urban Mobility',
    businessUnitId: 'bu-4',
    businessUnitName: 'Water & Industrial Effluent Treatment',
    location: 'Varanasi Clean Ganga Basin',
    state: 'Uttar Pradesh',
    esgCompletion: 83,
    brsrCompletion: 78,
    validationStatus: 'has_errors',
    approvalStatus: 'submitted',
    lastUpdated: '2026-03-24',
    leadPerson: 'Gautam Trivedi'
  }
];

export const MOCK_ESG_METRICS: ESGMetricItem[] = [
  // Environmental
  {
    id: 'em-1',
    category: 'environmental',
    subCategory: 'Emissions',
    name: 'Scope 1 GHG Direct Emissions',
    code: 'ENV-GHG-SC1',
    value: 14850,
    unit: 'tCO2e',
    previousValue: 16200,
    yoyChangePct: -8.33,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'validated',
    evidenceFile: 'Fuel_Combustion_Audit_FY26.pdf',
    remarks: 'Reduction driven by electrification of heavy site equipment.',
    validationStatus: 'valid',
    trend: [17800, 16900, 16200, 14850],
    brsrPrincipleMapping: 'P6 - Essential Indicator 1',
    sdgMapping: [13, 7]
  },
  {
    id: 'em-2',
    category: 'environmental',
    subCategory: 'Emissions',
    name: 'Scope 2 GHG Indirect Market-Based',
    code: 'ENV-GHG-SC2',
    value: 28400,
    unit: 'tCO2e',
    previousValue: 33100,
    yoyChangePct: -14.2,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Utility_Green_Tariff_Receipts.pdf',
    remarks: '42% power procured under Renewable Energy Open Access.',
    validationStatus: 'valid',
    trend: [39000, 36500, 33100, 28400],
    brsrPrincipleMapping: 'P6 - Essential Indicator 2',
    sdgMapping: [13, 7]
  },
  {
    id: 'em-3',
    category: 'environmental',
    subCategory: 'Emissions',
    name: 'Scope 3 Supply Chain & Logistics Emissions',
    code: 'ENV-GHG-SC3',
    value: 68200,
    unit: 'tCO2e',
    previousValue: 71500,
    yoyChangePct: -4.6,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'submitted',
    evidenceFile: 'Supplier_Transportation_Data_Log.xlsx',
    remarks: 'Calculated using Cat 1 Purchased Goods & Cat 4 Upstream Transportation.',
    validationStatus: 'warning',
    validationMessage: 'Tier-2 subcontractor fuel logs pending third-party sample check.',
    trend: [76000, 74200, 71500, 68200],
    brsrPrincipleMapping: 'P6 - Leadership Indicator 1',
    sdgMapping: [13, 12]
  },
  {
    id: 'em-4',
    category: 'environmental',
    subCategory: 'Energy',
    name: 'Total Electricity Consumption',
    code: 'ENV-ENG-ELEC',
    value: 124500,
    unit: 'GJ',
    previousValue: 129000,
    yoyChangePct: -3.48,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Energy_Audit_Cert_ISO50001.pdf',
    remarks: 'Facility certified under ISO 50001 energy management standard.',
    validationStatus: 'valid',
    trend: [134000, 131000, 129000, 124500],
    brsrPrincipleMapping: 'P6 - Essential Indicator 3',
    sdgMapping: [7, 12]
  },
  {
    id: 'em-5',
    category: 'environmental',
    subCategory: 'Energy',
    name: 'Renewable Energy Share in Total Consumption',
    code: 'ENV-ENG-REN',
    value: 46.8,
    unit: '%',
    previousValue: 38.2,
    yoyChangePct: 22.5,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Solar_Captive_Generation_Certificate.pdf',
    remarks: 'Exceeded FY26 target of 45% renewable energy transition.',
    validationStatus: 'valid',
    trend: [26, 32, 38.2, 46.8],
    brsrPrincipleMapping: 'P6 - Essential Indicator 4',
    sdgMapping: [7]
  },
  {
    id: 'em-6',
    category: 'environmental',
    subCategory: 'Water',
    name: 'Total Fresh Water Withdrawal',
    code: 'ENV-WAT-WTH',
    value: 384000,
    unit: 'kL',
    previousValue: 412000,
    yoyChangePct: -6.79,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'validated',
    evidenceFile: 'Groundwater_Flow_Meter_Telemetry.pdf',
    remarks: 'Groundwater abstraction reduced through rainwater harvesting recharge ponds.',
    validationStatus: 'valid',
    trend: [450000, 430000, 412000, 384000],
    brsrPrincipleMapping: 'P6 - Essential Indicator 5',
    sdgMapping: [6, 12]
  },
  {
    id: 'em-7',
    category: 'environmental',
    subCategory: 'Water',
    name: 'Water Recycled / Reused Ratio',
    code: 'ENV-WAT-REC',
    value: 58.4,
    unit: '%',
    previousValue: 51.2,
    yoyChangePct: 14.06,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Zero_Liquid_Discharge_Compliance.pdf',
    remarks: 'ZLD (Zero Liquid Discharge) systems operational at all heavy construction camps.',
    validationStatus: 'valid',
    trend: [41, 46, 51.2, 58.4],
    brsrPrincipleMapping: 'P6 - Essential Indicator 6',
    sdgMapping: [6, 14]
  },
  {
    id: 'em-8',
    category: 'environmental',
    subCategory: 'Waste',
    name: 'Hazardous Waste Generated & Safely Disposed',
    code: 'ENV-WST-HAZ',
    value: 84.5,
    unit: 'Metric Tonnes',
    previousValue: 92.1,
    yoyChangePct: -8.25,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'validated',
    evidenceFile: 'State_PCB_Manifest_Sludge_Oils.pdf',
    remarks: 'Manifests verified with State Pollution Control Board TSDF facility.',
    validationStatus: 'valid',
    trend: [105, 98, 92.1, 84.5],
    brsrPrincipleMapping: 'P6 - Essential Indicator 8',
    sdgMapping: [12, 11]
  },

  // Social
  {
    id: 'sm-1',
    category: 'social',
    subCategory: 'Workforce',
    name: 'Total Permanent Employees',
    code: 'SOC-EMP-TOT',
    value: 1420,
    unit: 'Nos.',
    previousValue: 1350,
    yoyChangePct: 5.18,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'HRMS_Payroll_Census_FY26.xlsx',
    remarks: 'Includes core technical, engineering, and supervisory staff.',
    validationStatus: 'valid',
    trend: [1200, 1280, 1350, 1420],
    brsrPrincipleMapping: 'P3 - Essential Indicator 1',
    sdgMapping: [8]
  },
  {
    id: 'sm-2',
    category: 'social',
    subCategory: 'Diversity',
    name: 'Female Representation in Workforce',
    code: 'SOC-DIV-FEM',
    value: 24.2,
    unit: '%',
    previousValue: 20.8,
    yoyChangePct: 16.34,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'validated',
    evidenceFile: 'DEI_Quarterly_Dashboard.pdf',
    remarks: 'Highest growth observed in engineering trainee intake cohorts.',
    validationStatus: 'valid',
    trend: [16.5, 18.4, 20.8, 24.2],
    brsrPrincipleMapping: 'P5 - Essential Indicator 1',
    sdgMapping: [5, 10]
  },
  {
    id: 'sm-3',
    category: 'social',
    subCategory: 'Safety',
    name: 'Lost Time Injury Frequency Rate (LTIFR)',
    code: 'SOC-SAF-LTIFR',
    value: 0.12,
    unit: 'per mn hrs worked',
    previousValue: 0.18,
    yoyChangePct: -33.3,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Safety_EHS_Monthly_Audit_Logs.pdf',
    remarks: 'Zero fatalities recorded across 18.4 million safe man-hours worked.',
    validationStatus: 'valid',
    trend: [0.28, 0.22, 0.18, 0.12],
    brsrPrincipleMapping: 'P3 - Essential Indicator 4',
    sdgMapping: [3, 8]
  },
  {
    id: 'sm-4',
    category: 'social',
    subCategory: 'Training',
    name: 'Average ESG & Safety Training Hours per Employee',
    code: 'SOC-TRN-HRS',
    value: 36.4,
    unit: 'Hours',
    previousValue: 31.0,
    yoyChangePct: 17.41,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'LMS_Training_Completion_Records.pdf',
    remarks: 'Mandatory behavioral safety, human rights, and anti-bribery modules.',
    validationStatus: 'valid',
    trend: [24, 28, 31, 36.4],
    brsrPrincipleMapping: 'P3 - Essential Indicator 2',
    sdgMapping: [4, 8]
  },
  {
    id: 'sm-5',
    category: 'social',
    subCategory: 'Community',
    name: 'CSR Spend & Community Beneficiaries',
    code: 'SOC-CSR-SPN',
    value: 18.5,
    unit: '₹ Crore',
    previousValue: 16.2,
    yoyChangePct: 14.19,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'validated',
    evidenceFile: 'CSR_Committee_Approved_Impact_Report.pdf',
    remarks: 'Benefited 64,000+ villagers in vocational skilling and clean water access.',
    validationStatus: 'valid',
    trend: [12.8, 14.5, 16.2, 18.5],
    brsrPrincipleMapping: 'P8 - Essential Indicator 1',
    sdgMapping: [1, 3, 4, 6]
  },

  // Governance
  {
    id: 'gm-1',
    category: 'governance',
    subCategory: 'Ethics',
    name: 'Anti-Corruption & Anti-Bribery Policy Coverage',
    code: 'GOV-ETH-POL',
    value: '100% Operations Covered',
    unit: 'Coverage',
    previousValue: '100% Operations Covered',
    yoyChangePct: 0,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Board_Approved_Code_Of_Conduct_2025.pdf',
    remarks: 'Annual affirmation received from 100% of employees and key suppliers.',
    validationStatus: 'valid',
    trend: [100, 100, 100, 100],
    brsrPrincipleMapping: 'P1 - Essential Indicator 1',
    sdgMapping: [16]
  },
  {
    id: 'gm-2',
    category: 'governance',
    subCategory: 'Whistleblower',
    name: 'Whistleblower Grievances Received & Resolved',
    code: 'GOV-WBL-GRV',
    value: '14 Received / 14 Resolved',
    unit: 'Cases',
    previousValue: '11 Received / 11 Resolved',
    yoyChangePct: 0,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'Ombudsman_Quarterly_Board_Report.pdf',
    remarks: '100% investigated within mandated 30-day timeline with zero retaliation.',
    validationStatus: 'valid',
    trend: [9, 12, 11, 14],
    brsrPrincipleMapping: 'P1 - Essential Indicator 3',
    sdgMapping: [16]
  },
  {
    id: 'gm-3',
    category: 'governance',
    subCategory: 'Cybersecurity',
    name: 'Cybersecurity Audits & Zero Major Breaches',
    code: 'GOV-CYB-SEC',
    value: '0 Breaches / ISO 27001 Active',
    unit: 'Security Status',
    previousValue: '0 Breaches',
    yoyChangePct: 0,
    reportingPeriod: 'FY 2025-26',
    projectCode: 'SMP-500',
    status: 'approved',
    evidenceFile: 'ISO27001_Audit_Attestation.pdf',
    remarks: 'Third-party red teaming and SOC 2 Type II assurance maintained.',
    validationStatus: 'valid',
    trend: [0, 0, 0, 0],
    brsrPrincipleMapping: 'P9 - Essential Indicator 2',
    sdgMapping: [9, 16]
  }
];

export const MOCK_VALIDATION_ALERTS: ValidationAlert[] = [
  {
    id: 'val-101',
    recordId: 'em-3',
    metric: 'Scope 3 Supply Chain Logistics',
    project: 'Solar Mega-Park 500MW (SMP-500)',
    businessUnit: 'Renewables & Power Transmission',
    subsidiary: 'Apex Heavy Engineering & Construction',
    category: 'Environmental',
    value: '68,200 tCO2e',
    previousValue: '71,500 tCO2e',
    rule: 'Subcontractor Logistics Variance Check',
    severity: 'warning',
    status: 'open',
    detectedAt: '2026-03-27 14:32',
    details: 'Tier-2 inland trucking emission factors submitted use DEFRA 2024 rather than Indian CEA / GHG Protocol standard.',
    justification: 'Requested contractor update with localized emission factors.'
  },
  {
    id: 'val-102',
    recordId: 'em-wat-wwrp',
    metric: 'Effluent BOD Discharge Concentration',
    project: 'Wastewater Reclamation Plant (WWRP-02)',
    businessUnit: 'Water & Industrial Effluent Treatment',
    subsidiary: 'Apex Smart Infrastructure & Urban Mobility',
    category: 'Environmental',
    value: '38.4 mg/L',
    previousValue: '18.2 mg/L',
    rule: 'Pollution Control Limit & YoY Anomaly (>50% jump)',
    severity: 'error',
    status: 'open',
    detectedAt: '2026-03-28 09:15',
    details: 'Discharge BOD exceeds the site CPCB consent-to-operate threshold of 30 mg/L during the monsoon bypass testing cycle.',
    justification: 'Plant supervisor re-calibrating membrane bioreactor telemetry.'
  },
  {
    id: 'val-103',
    recordId: 'sm-turnover',
    metric: 'Contractor Worker Turnover Rate',
    project: 'Green Hydrogen Electrolyzer Plant (GH2-01)',
    businessUnit: 'Hydrocarbon & Heavy EPC',
    subsidiary: 'Apex Heavy Engineering & Construction',
    category: 'Social',
    value: '42.6%',
    previousValue: '24.1%',
    rule: 'Abnormal Turnover Spike Threshold (>35%)',
    severity: 'warning',
    status: 'under_review',
    detectedAt: '2026-03-26 11:40',
    details: 'Civil construction phase completion triggered demobilization of specialized piping labor.',
    justification: 'Civil contract concluded as scheduled in project milestone chart.'
  },
  {
    id: 'val-104',
    recordId: 'gov-board',
    metric: 'Independent Director Committee Participation',
    project: 'Apex Infrastructure Group Entity',
    businessUnit: 'Corporate Secretariat',
    subsidiary: 'Apex Heavy Engineering & Construction',
    category: 'Governance',
    value: '88% Attendance',
    previousValue: '94% Attendance',
    rule: 'SEBI LODR Regulation 25 Compliance Check',
    severity: 'info',
    status: 'accepted_with_justification',
    detectedAt: '2026-03-25 16:50',
    details: 'One director missed specialized safety audit due to international medical leave. Quorum was maintained.',
    justification: 'Leave granted by Board Chairman; valid quorum confirmed.'
  }
];

export const MOCK_APPROVALS: ApprovalRecord[] = [
  {
    id: 'appr-01',
    projectCode: 'SMP-500',
    projectName: 'Solar Mega-Park 500MW Facility',
    subsidiary: 'Apex Heavy Engineering & Construction',
    businessUnit: 'Renewables & Power Transmission',
    category: 'Environmental',
    reportingPeriod: 'FY 2025-26',
    submittedBy: 'Rajesh Verma (Project Lead)',
    submittedAt: '2026-03-25 10:30',
    validationStatus: 'clean',
    currentLevelIndex: 3,
    overallStatus: 'under_review',
    evidenceCount: 8,
    summaryHighlights: 'Scope 1 direct emissions down 8.3%; Renewable energy captive share reached 46.8% with zero safety incidents.',
    steps: [
      {
        level: 'project',
        label: 'Project Data Entry',
        assignedRole: 'project_user',
        status: 'approved',
        actionBy: 'Rajesh Verma',
        actionAt: '2026-03-25 10:30',
        comments: 'All utility meters, water telemetry and TSDF hazardous waste manifests verified.'
      },
      {
        level: 'bu',
        label: 'BU Review & Approval',
        assignedRole: 'bu_manager',
        status: 'approved',
        actionBy: 'Sunita Rao',
        actionAt: '2026-03-26 14:15',
        comments: 'Verified against BU power generation logs. Data quality is solid.'
      },
      {
        level: 'subsidiary',
        label: 'Subsidiary Admin Signoff',
        assignedRole: 'subsidiary_admin',
        status: 'approved',
        actionBy: 'Vikramaditya Patel',
        actionAt: '2026-03-27 16:45',
        comments: 'Subsidiary consolidation completed. Forwarded to Group ESG.'
      },
      {
        level: 'esg_team',
        label: 'Group ESG Team Validation',
        assignedRole: 'esg_team',
        status: 'in_progress',
        comments: 'Conducting final cross-check with CEA grid emission factor updates.'
      },
      {
        level: 'group_admin',
        label: 'Group Executive Approval',
        assignedRole: 'group_admin',
        status: 'pending'
      },
      {
        level: 'final',
        label: 'Final BRSR Publication',
        assignedRole: 'management',
        status: 'pending'
      }
    ]
  },
  {
    id: 'appr-02',
    projectCode: 'GH2-01',
    projectName: 'Green Hydrogen Electrolyzer Pilot Plant',
    subsidiary: 'Apex Heavy Engineering & Construction',
    businessUnit: 'Hydrocarbon & Heavy EPC',
    category: 'Social',
    reportingPeriod: 'FY 2025-26',
    submittedBy: 'Manish Chawla (Project Lead)',
    submittedAt: '2026-03-24 12:10',
    validationStatus: 'warnings_flagged',
    currentLevelIndex: 1,
    overallStatus: 'correction_required',
    evidenceCount: 4,
    summaryHighlights: 'Training hours logged at 34 hrs/worker, but contractor workforce turnover explanation needed.',
    steps: [
      {
        level: 'project',
        label: 'Project Data Entry',
        assignedRole: 'project_user',
        status: 'approved',
        actionBy: 'Manish Chawla',
        actionAt: '2026-03-24 12:10',
        comments: 'Submitted initial Q4 social metric figures.'
      },
      {
        level: 'bu',
        label: 'BU Review & Approval',
        assignedRole: 'bu_manager',
        status: 'rejected',
        actionBy: 'Devendra Joshi',
        actionAt: '2026-03-25 09:30',
        comments: 'Correction required: Explain the spike in contractor labor turnover and attach training attendance signoff sheets.'
      },
      {
        level: 'subsidiary',
        label: 'Subsidiary Admin Signoff',
        assignedRole: 'subsidiary_admin',
        status: 'pending'
      },
      {
        level: 'esg_team',
        label: 'Group ESG Team Validation',
        assignedRole: 'esg_team',
        status: 'pending'
      },
      {
        level: 'group_admin',
        label: 'Group Executive Approval',
        assignedRole: 'group_admin',
        status: 'pending'
      },
      {
        level: 'final',
        label: 'Final BRSR Publication',
        assignedRole: 'management',
        status: 'pending'
      }
    ]
  },
  {
    id: 'appr-03',
    projectCode: 'METRO-L3',
    projectName: 'Urban Elevated Metro Corridor Phase 3',
    subsidiary: 'Apex Smart Infrastructure & Urban Mobility',
    businessUnit: 'Metro Rail & Transit Systems',
    category: 'Governance',
    reportingPeriod: 'FY 2025-26',
    submittedBy: 'Pooja Hegde (Project Lead)',
    submittedAt: '2026-03-26 15:40',
    validationStatus: 'clean',
    currentLevelIndex: 4,
    overallStatus: 'validated',
    evidenceCount: 6,
    summaryHighlights: 'Zero anti-corruption cases, 100% subcontractor compliance audits completed, ISO 27001 reaffirmed.',
    steps: [
      {
        level: 'project',
        label: 'Project Data Entry',
        assignedRole: 'project_user',
        status: 'approved',
        actionBy: 'Pooja Hegde',
        actionAt: '2026-03-26 15:40'
      },
      {
        level: 'bu',
        label: 'BU Review & Approval',
        assignedRole: 'bu_manager',
        status: 'approved',
        actionBy: 'Karan Singhal',
        actionAt: '2026-03-27 10:15'
      },
      {
        level: 'subsidiary',
        label: 'Subsidiary Admin Signoff',
        assignedRole: 'subsidiary_admin',
        status: 'approved',
        actionBy: 'Meera Krishnan',
        actionAt: '2026-03-27 18:20'
      },
      {
        level: 'esg_team',
        label: 'Group ESG Team Validation',
        assignedRole: 'esg_team',
        status: 'approved',
        actionBy: 'Dr. Ananya Sen',
        actionAt: '2026-03-28 11:00',
        comments: 'Fully verified against SEBI Governance disclosures. Ready for Group Executive signoff.'
      },
      {
        level: 'group_admin',
        label: 'Group Executive Approval',
        assignedRole: 'group_admin',
        status: 'in_progress'
      },
      {
        level: 'final',
        label: 'Final BRSR Publication',
        assignedRole: 'management',
        status: 'pending'
      }
    ]
  }
];

export const MOCK_BRSR_SECTION_A = {
  entityDetails: {
    cin: 'L99999MH2002PLC138924',
    name: 'Apex Infrastructure Group Limited',
    incorporationYear: '2002',
    registeredOffice: 'Apex Tower, Bandra-Kurla Complex, Mumbai, Maharashtra - 400051',
    corporateAddress: 'Apex Global Centre, Outer Ring Road, Bengaluru, Karnataka - 560103',
    email: 'esg.compliance@apexinfratech.com',
    telephone: '+91 22 6988 5000',
    website: 'www.apexinfratech.com',
    financialYear: '2025-26 (April 1, 2025 to March 31, 2026)',
    stockExchanges: 'National Stock Exchange of India (NSE) & BSE Limited',
    paidUpCapital: '₹ 1,412.50 Crore',
    contactPerson: 'Arvind Mehra, Group Executive VP & Company Secretary',
    reportingBoundary: 'Consolidated (Holding Company + 3 Key Subsidiaries + 5 Joint Ventures)',
    assuranceProvider: 'DNV Business Assurance India Private Limited',
    assuranceType: 'Reasonable Assurance for BRSR Core (Annexure 2), Limited Assurance for Comprehensive BRSR'
  },
  productsAndServices: [
    { nicCode: '4210', productDescription: 'Construction of roads, railways and metro rail systems', turnoverPct: 38.5 },
    { nicCode: '4220', productDescription: 'Construction of utility projects (renewables, water pipelines, power grids)', turnoverPct: 34.2 },
    { nicCode: '2811', productDescription: 'Manufacture of heavy industrial components & green hydrogen electrolyzers', turnoverPct: 18.6 },
    { nicCode: '7112', productDescription: 'Engineering design and environmental consultancy services', turnoverPct: 8.7 }
  ],
  operations: {
    nationalPlants: 24,
    nationalOffices: 48,
    internationalPlants: 3,
    internationalOffices: 7,
    keyMarkets: 'India, Middle East (UAE, Saudi Arabia), South-East Asia'
  },
  employeesAndWorkers: {
    totalEmployees: 14850,
    femaleEmployees: 3594,
    femaleEmployeePct: 24.2,
    differentlyAbled: 142,
    permanentWorkers: 32400,
    contractWorkers: 46800,
    turnoverRate: 7.8
  },
  subsidiaryHoldings: [
    { name: 'Apex Heavy Engineering & Construction Ltd', relationship: 'Subsidiary', equityShare: 100, participatesInBRSR: 'Yes (Included in Boundary)' },
    { name: 'Apex Smart Infrastructure & Urban Mobility Ltd', relationship: 'Subsidiary', equityShare: 88.5, participatesInBRSR: 'Yes (Included in Boundary)' },
    { name: 'Apex Green Energy & Utility Services Ltd', relationship: 'Subsidiary', equityShare: 74.0, participatesInBRSR: 'Yes (Included in Boundary)' },
    { name: 'Gulf Trans-Grid Consortium W.L.L', relationship: 'Joint Venture', equityShare: 50.0, participatesInBRSR: 'No (Separate Regional Filing)' }
  ],
  csrDetails: {
    turnoverCr: 48200,
    netProfitCr: 3950,
    prescribedCsrCr: 79.0,
    actualCsrSpentCr: 84.5,
    keyFocusAreas: 'Rural Clean Water Access, Skill Development, Women STEM Education, Biodiversity Conservation'
  },
  grievances: [
    { stakeholder: 'Communities', received: 18, resolved: 18, pending: 0 },
    { stakeholder: 'Investors / Shareholders', received: 42, resolved: 42, pending: 0 },
    { stakeholder: 'Employees and Workers', received: 56, resolved: 54, pending: 2 },
    { stakeholder: 'Customers / Clients', received: 8, resolved: 8, pending: 0 },
    { stakeholder: 'Value Chain Partners', received: 12, resolved: 12, pending: 0 }
  ]
};

export const MOCK_BRSR_PRINCIPLES = [
  {
    number: 1,
    name: 'Ethics, Transparency and Accountability',
    shortName: 'Ethics & Integrity',
    description: 'Businesses should conduct and govern themselves with integrity, and in a manner that is Ethical, Transparent and Accountable.',
    essentialCount: 8,
    leadershipCount: 4,
    essentialCompleted: 8,
    leadershipCompleted: 3,
    totalCompletion: 92,
    status: 'validated' as const
  },
  {
    number: 2,
    name: 'Sustainable and Safe Goods and Services',
    shortName: 'Product Stewardship',
    description: 'Businesses should provide goods and services in a manner that is sustainable and safe throughout their life cycle.',
    essentialCount: 6,
    leadershipCount: 4,
    essentialCompleted: 5,
    leadershipCompleted: 3,
    totalCompletion: 80,
    status: 'under_review' as const
  },
  {
    number: 3,
    name: 'Employee Well-being and Human Development',
    shortName: 'Workforce Well-being',
    description: 'Businesses should respect and promote the well-being of all employees, including those in their value chains.',
    essentialCount: 11,
    leadershipCount: 6,
    essentialCompleted: 11,
    leadershipCompleted: 5,
    totalCompletion: 94,
    status: 'validated' as const
  },
  {
    number: 4,
    name: 'Responsiveness to All Stakeholders',
    shortName: 'Stakeholder Engagement',
    description: 'Businesses should respect the interests of and be responsive to all its stakeholders.',
    essentialCount: 4,
    leadershipCount: 3,
    essentialCompleted: 4,
    leadershipCompleted: 2,
    totalCompletion: 86,
    status: 'validated' as const
  },
  {
    number: 5,
    name: 'Human Rights in Operations and Value Chain',
    shortName: 'Human Rights',
    description: 'Businesses should respect and promote human rights.',
    essentialCount: 7,
    leadershipCount: 4,
    essentialCompleted: 7,
    leadershipCompleted: 3,
    totalCompletion: 91,
    status: 'validated' as const
  },
  {
    number: 6,
    name: 'Protection and Restoration of the Environment',
    shortName: 'Environment & Climate',
    description: 'Businesses should respect and make efforts to protect and restore the environment.',
    essentialCount: 12,
    leadershipCount: 8,
    essentialCompleted: 11,
    leadershipCompleted: 7,
    totalCompletion: 90,
    status: 'under_review' as const
  },
  {
    number: 7,
    name: 'Responsible Public Policy Engagement',
    shortName: 'Policy Advocacy',
    description: 'Businesses, when engaging in influencing public and regulatory policy, should do so in a manner that is responsible and transparent.',
    essentialCount: 3,
    leadershipCount: 2,
    essentialCompleted: 3,
    leadershipCompleted: 2,
    totalCompletion: 100,
    status: 'approved' as const
  },
  {
    number: 8,
    name: 'Inclusive Growth and Equitable Development',
    shortName: 'Inclusive Growth & CSR',
    description: 'Businesses should promote inclusive growth and equitable development.',
    essentialCount: 5,
    leadershipCount: 4,
    essentialCompleted: 5,
    leadershipCompleted: 3,
    totalCompletion: 89,
    status: 'validated' as const
  },
  {
    number: 9,
    name: 'Consumer Value and Responsible Relations',
    shortName: 'Customer Value',
    description: 'Businesses should engage with and provide value to their consumers in a responsible manner.',
    essentialCount: 4,
    leadershipCount: 3,
    essentialCompleted: 4,
    leadershipCompleted: 2,
    totalCompletion: 86,
    status: 'validated' as const
  }
];

export const MOCK_BRSR_INDICATORS: BRSRIndicator[] = [
  // Principle 6 (Environment)
  {
    code: 'P6-E1',
    principle: 6,
    type: 'essential',
    question: 'Details of total energy consumption (in Joules or multiples) and energy intensity per rupee of turnover.',
    unit: 'GJ / ₹ Cr',
    currentValue: '124,500 GJ (Intensity: 2.58 GJ/₹ Cr)',
    previousValue: '129,000 GJ (Intensity: 2.94 GJ/₹ Cr)',
    dataType: 'text',
    status: 'validated',
    evidenceRequired: true,
    evidenceAttached: 'Energy_Audit_Cert_ISO50001.pdf',
    reviewerNotes: 'Third party ISO 50001 auditor cert verified.',
    lastUpdated: '2026-03-27',
    assignedRole: 'esg_team',
    esgMetricSource: 'ENV-ENG-ELEC'
  },
  {
    code: 'P6-E2',
    principle: 6,
    type: 'essential',
    question: 'Does the entity have any sites / facilities identified as having operations in/near sensitive areas (national parks, wildlife sanctuaries, etc.)?',
    dataType: 'boolean',
    currentValue: 'No',
    previousValue: 'No',
    status: 'approved',
    evidenceRequired: true,
    evidenceAttached: 'MoEFCC_Environmental_Clearance_Register.pdf',
    reviewerNotes: 'Geofence coordinates audited against Protected Area GIS.',
    lastUpdated: '2026-03-26',
    assignedRole: 'esg_team'
  },
  {
    code: 'P6-E3',
    principle: 6,
    type: 'essential',
    question: 'Details of total water withdrawal by source (Groundwater, Surface water, Municipal supply, Seawater) and water consumption intensity.',
    unit: 'kL / ₹ Cr',
    currentValue: '384,000 kL (Intensity: 7.96 kL/₹ Cr)',
    previousValue: '412,000 kL (Intensity: 9.38 kL/₹ Cr)',
    dataType: 'text',
    status: 'validated',
    evidenceRequired: true,
    evidenceAttached: 'Groundwater_Flow_Meter_Telemetry.pdf',
    reviewerNotes: 'Telemetry logs checked against state water permits.',
    lastUpdated: '2026-03-28',
    assignedRole: 'esg_team',
    esgMetricSource: 'ENV-WAT-WTH'
  },
  {
    code: 'P6-E4',
    principle: 6,
    type: 'essential',
    question: 'Details of air emissions (other than GHG emissions) like NOx, SOx, Particulate matter (PM) and Persistent Organic Pollutants (POP).',
    unit: 'mg/Nm3',
    currentValue: 'PM: 24.2, NOx: 41.8, SOx: 32.5 (All well below CPCB limits)',
    previousValue: 'PM: 28.5, NOx: 46.2, SOx: 36.1',
    dataType: 'text',
    status: 'validated',
    evidenceRequired: true,
    evidenceAttached: 'Continuous_Air_Emission_Monitoring_Logs.pdf',
    reviewerNotes: 'CEMS connected real-time to CPCB servers.',
    lastUpdated: '2026-03-25',
    assignedRole: 'esg_team'
  },
  {
    code: 'P6-E5',
    principle: 6,
    type: 'essential',
    question: 'Details of greenhouse gas emissions (Scope 1 and Scope 2: emissions in metric tonnes of CO2 equivalent) and GHG intensity.',
    unit: 'tCO2e / ₹ Cr',
    currentValue: 'Scope 1: 14,850 tCO2e | Scope 2: 28,400 tCO2e | Total: 43,250 tCO2e (Intensity: 0.89 tCO2e/₹ Cr)',
    previousValue: 'Scope 1: 16,200 tCO2e | Scope 2: 33,100 tCO2e | Total: 49,300 tCO2e (Intensity: 1.12 tCO2e/₹ Cr)',
    dataType: 'text',
    status: 'validated',
    evidenceRequired: true,
    evidenceAttached: 'GHG_Protocol_Assurance_Statement_DNV.pdf',
    reviewerNotes: 'Assurance statement by DNV India verified against BRSR Core requirements.',
    lastUpdated: '2026-03-27',
    assignedRole: 'esg_team',
    esgMetricSource: 'ENV-GHG-SC1'
  },
  {
    code: 'P6-E6',
    principle: 6,
    type: 'essential',
    question: 'Briefly describe any project related to reducing greenhouse gas emissions and green energy transition undertaken by the entity.',
    dataType: 'text',
    currentValue: 'Commissioned 12 MW rooftop captive solar array; replaced 85 diesel gensets with high-efficiency battery energy storage system (BESS); transition of 45% heavy fleet to biodiesel B20 blends.',
    status: 'approved',
    evidenceRequired: false,
    lastUpdated: '2026-03-25',
    assignedRole: 'esg_team'
  },
  {
    code: 'P6-L1',
    principle: 6,
    type: 'leadership',
    question: 'Break-up of Scope 3 emissions & its relevant categories pursuant to GHG Protocol Corporate Value Chain Standard.',
    unit: 'tCO2e',
    currentValue: '68,200 tCO2e across Category 1 (Purchased Goods) and Category 4 (Upstream Freight)',
    previousValue: '71,500 tCO2e',
    dataType: 'text',
    status: 'under_review',
    evidenceRequired: true,
    evidenceAttached: 'Scope3_Upstream_Supply_Chain_Inventory.xlsx',
    reviewerNotes: 'Pending final review of tier-2 supplier fuel data.',
    lastUpdated: '2026-03-26',
    assignedRole: 'esg_team',
    esgMetricSource: 'ENV-GHG-SC3'
  },

  // Principle 3 (Employees)
  {
    code: 'P3-E1',
    principle: 3,
    type: 'essential',
    question: 'Details of measures for well-being of employees & workers (Health insurance, Accident insurance, Maternity benefits, Paternity benefits, Day care facilities).',
    dataType: 'text',
    currentValue: '100% permanent employees and 100% on-roll workers covered under comprehensive cashless health and personal accident insurance.',
    previousValue: '100% covered',
    status: 'approved',
    evidenceRequired: true,
    evidenceAttached: 'Employee_Benefit_Policy_Document_FY26.pdf',
    reviewerNotes: 'Group medical insurance master policy copy verified.',
    lastUpdated: '2026-03-27',
    assignedRole: 'bu_manager'
  },
  {
    code: 'P3-E4',
    principle: 3,
    type: 'essential',
    question: 'Details of safety incidents: Lost Time Injury Frequency Rate (LTIFR), Total recordable work-related injuries, Fatalities, High consequence injuries.',
    unit: 'per mn hrs worked',
    currentValue: 'LTIFR: 0.12 | Fatalities: 0 | Work-related injuries: 4 (all minor first-aid)',
    previousValue: 'LTIFR: 0.18 | Fatalities: 0 | Work-related injuries: 7',
    dataType: 'text',
    status: 'approved',
    evidenceRequired: true,
    evidenceAttached: 'Safety_EHS_Monthly_Audit_Logs.pdf',
    reviewerNotes: 'Verified with Directorate of Industrial Safety & Health quarterly returns.',
    lastUpdated: '2026-03-28',
    assignedRole: 'esg_team',
    esgMetricSource: 'SOC-SAF-LTIFR'
  }
];

export const MOCK_SDGS: SDGItem[] = [
  { number: 1, title: 'No Poverty', color: '#E5243B', targetCount: 7, mappedMetricsCount: 3, progressScore: 84, initiatives: ['Rural vocational training centers in project catchments', 'Direct procurement from smallholder micro-enterprises'] },
  { number: 2, title: 'Zero Hunger', color: '#DDA63A', targetCount: 8, mappedMetricsCount: 2, progressScore: 78, initiatives: ['Midday nutritional support for construction migrant families'] },
  { number: 3, title: 'Good Health & Well-being', color: '#4C9F38', targetCount: 13, mappedMetricsCount: 6, progressScore: 94, initiatives: ['Zero fatality vision', 'On-site tele-health clinics', '100% health insurance coverage'] },
  { number: 4, title: 'Quality Education', color: '#C5192D', targetCount: 10, mappedMetricsCount: 5, progressScore: 88, initiatives: ['Apex Science & Tech scholarship for girls in STEM', 'Apprenticeship skilling programs'] },
  { number: 5, title: 'Gender Equality', color: '#FF3A21', targetCount: 9, mappedMetricsCount: 4, progressScore: 82, initiatives: ['Target 30% women in engineering roles by 2028', 'POSH committee oversight and zero tolerance'] },
  { number: 6, title: 'Clean Water & Sanitation', color: '#26BDE2', targetCount: 8, mappedMetricsCount: 7, progressScore: 92, initiatives: ['Zero Liquid Discharge at 100% heavy construction sites', '1.8 million kL water recharged through check dams'] },
  { number: 7, title: 'Affordable & Clean Energy', color: '#FCC30B', targetCount: 5, mappedMetricsCount: 8, progressScore: 96, initiatives: ['500MW solar park deployment', '46.8% renewable electricity captive consumption', 'Electrification of heavy construction fleet'] },
  { number: 8, title: 'Decent Work & Economic Growth', color: '#A21942', targetCount: 12, mappedMetricsCount: 9, progressScore: 95, initiatives: ['Fair living wage compliance', 'Equal pay audits', 'Supply chain human rights code'] },
  { number: 9, title: 'Industry, Innovation & Infrastructure', color: '#FD6925', targetCount: 8, mappedMetricsCount: 8, progressScore: 91, initiatives: ['Green hydrogen electrolyzer pilots', 'Low-carbon geopolymer concrete use in metro projects'] },
  { number: 10, title: 'Reduced Inequalities', color: '#DD1367', targetCount: 10, mappedMetricsCount: 4, progressScore: 80, initiatives: ['Affirmative hiring for differently-abled workers', 'Supplier diversity programs'] },
  { number: 11, title: 'Sustainable Cities & Communities', color: '#FD9D24', targetCount: 10, mappedMetricsCount: 6, progressScore: 89, initiatives: ['Urban Metro Phase 3 mass transit', 'Fly-ash utilization in 94% civil structures'] },
  { number: 12, title: 'Responsible Consumption & Production', color: '#BF8B2E', targetCount: 11, mappedMetricsCount: 7, progressScore: 87, initiatives: ['Hazardous waste 100% co-processed in cement kilns', 'Circular economy scrap metal recycling'] },
  { number: 13, title: 'Climate Action', color: '#3F7E44', targetCount: 5, mappedMetricsCount: 10, progressScore: 93, initiatives: ['Science-Based Targets initiative (SBTi) net-zero commitment', 'TCFD climate scenario risk assessment'] },
  { number: 14, title: 'Life Below Water', color: '#0A97D9', targetCount: 10, mappedMetricsCount: 3, progressScore: 85, initiatives: ['Zero untreated effluent to marine or river bodies', 'Mangrove conservation in coastal port projects'] },
  { number: 15, title: 'Life on Land', color: '#56C02B', targetCount: 12, mappedMetricsCount: 4, progressScore: 86, initiatives: ['1.2 million saplings planted under compensatory afforestation', 'Biodiversity action plans for sensitive corridors'] },
  { number: 16, title: 'Peace, Justice & Strong Institutions', color: '#00689D', targetCount: 12, mappedMetricsCount: 6, progressScore: 98, initiatives: ['100% board anti-corruption training', 'Independent whistle-blower mechanism', 'Strict vendor code of conduct'] },
  { number: 17, title: 'Partnerships for the Goals', color: '#19486A', targetCount: 19, mappedMetricsCount: 5, progressScore: 90, initiatives: ['Active participation in CII ESG leadership forum', 'UN Global Compact participant signatory'] }
];

export const MOCK_AUDIT_LOGS: AuditTrailRecord[] = [
  {
    id: 'aud-901',
    timestamp: '2026-03-28 11:20:14',
    userName: 'Dr. Ananya Sen',
    userRole: 'ESG / Sustainability Team',
    action: 'Validated',
    entity: 'BRSR Indicator',
    entityId: 'P6-E5 (GHG Emissions)',
    previousValue: 'Draft',
    newValue: 'Validated with DNV Reasonable Assurance Statement',
    ipAddress: '10.240.12.84'
  },
  {
    id: 'aud-902',
    timestamp: '2026-03-28 09:45:00',
    userName: 'Gautam Trivedi',
    userRole: 'Project User',
    action: 'Submitted',
    entity: 'Project ESG Record',
    entityId: 'WWRP-02 (Water Treatment)',
    previousValue: 'Draft',
    newValue: 'Submitted to BU Reviewer',
    ipAddress: '172.16.4.19'
  },
  {
    id: 'aud-903',
    timestamp: '2026-03-27 16:48:22',
    userName: 'Vikramaditya Patel',
    userRole: 'Subsidiary Admin',
    action: 'Approved',
    entity: 'Approval Request',
    entityId: 'appr-01 (SMP-500 Environmental)',
    previousValue: 'Under BU Review',
    newValue: 'Approved & Forwarded to Group ESG',
    ipAddress: '10.240.10.15'
  },
  {
    id: 'aud-904',
    timestamp: '2026-03-27 14:32:05',
    userName: 'Validation Rule Engine',
    userRole: 'Automated System',
    action: 'Updated',
    entity: 'Validation Rule Flag',
    entityId: 'val-101 (Scope 3 Logistics)',
    previousValue: 'Clean',
    newValue: 'Warning: DEFRA factor vs Indian CEA protocol variance',
    ipAddress: '127.0.0.1 (Internal Service)'
  },
  {
    id: 'aud-905',
    timestamp: '2026-03-26 15:10:40',
    userName: 'Rajesh Verma',
    userRole: 'Project User',
    action: 'Uploaded Evidence',
    entity: 'ESG Evidence Document',
    entityId: 'Solar_Captive_Generation_Certificate.pdf',
    newValue: 'Hash: a9f83...bc12 (Size: 2.4 MB)',
    ipAddress: '192.168.1.105'
  },
  {
    id: 'aud-906',
    timestamp: '2026-03-25 18:00:11',
    userName: 'Arvind Mehra',
    userRole: 'Group Admin',
    action: 'Generated Report',
    entity: 'BRSR Report Draft',
    entityId: 'BRSR-Core-FY26-Draft-v1.4',
    newValue: 'Full SEBI Annexure 1 & 2 Compiled PDF',
    ipAddress: '10.240.10.2'
  }
];

export const MOCK_REPORTS = [
  {
    id: 'rep-01',
    title: 'SEBI BRSR Comprehensive Annual Report FY 2025-26',
    type: 'SEBI Mandatory Regulatory Filing',
    format: 'PDF / XBRL Ready',
    generatedAt: '2026-03-28 11:30',
    fileSize: '4.8 MB',
    status: 'Final Approved',
    reportingBoundary: 'Consolidated (All Subsidiaries + JVs)',
    downloadUrl: '#'
  },
  {
    id: 'rep-02',
    title: 'BRSR Core Key Attributes & Assurance Pack (Annexure 2)',
    type: 'Audited BRSR Core Disclosures',
    format: 'PDF + Excel Data Book',
    generatedAt: '2026-03-27 17:15',
    fileSize: '2.9 MB',
    status: 'Ready for Board',
    reportingBoundary: 'Top 1000 Listed Entities Scope',
    downloadUrl: '#'
  },
  {
    id: 'rep-03',
    title: 'Executive ESG Performance & Climate Risk Summary',
    type: 'Board & Management Briefing',
    format: 'Interactive Presentation PDF',
    generatedAt: '2026-03-26 14:00',
    fileSize: '3.4 MB',
    status: 'Reviewed',
    reportingBoundary: 'Apex Infrastructure Group Executive Level',
    downloadUrl: '#'
  },
  {
    id: 'rep-04',
    title: 'UN SDGs Alignment & Corporate Impact Ledger',
    type: 'Global Impact Disclosures',
    format: 'PDF / CSV',
    generatedAt: '2026-03-25 10:20',
    fileSize: '1.8 MB',
    status: 'Validated',
    reportingBoundary: '17 UN Sustainable Development Goals',
    downloadUrl: '#'
  }
];
